cs:

config:
	git config -l

count:
	ls -al | grep "RunVoting.in"   | wc
	ls -al | grep "RunVoting.out"  | wc
	ls -al | grep "TestVoting.c++" | wc
	ls -al | grep "TestVoting.out" | wc

log:
	git log

pull:
	git pull

status:
	git branch
	git remote
	git status
